apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: minimalist-portfolio-ns
type: Opaque
stringData:
  PROXY_HEADER: "pbxCzc_YRVfWiY_tOxhp-9QvpiVY1-nm"
  GOOGLE_CLOUD_PROJECT: "godl-project"
